package com.franz.easymusicplayer.bean

import java.util.*

data class AccountInfoBean(
    var level:Int,
    val accountStatus: Int,
    val allSubscribedCount: Int,
    val artistIdentity: List<Any>,
    val authStatus: Int,
    val authority: Int,
    val avatarDetail: Any,
    val avatarImgId: Long,
    val avatarImgIdStr: String,
    val avatarImgId_str: String,
    val avatarUrl: String,
    val backgroundImgId: Long,
    val backgroundImgIdStr: String,
    val backgroundUrl: String,
    val birthday: Long,
    val blacklist: Boolean,
    val cCount: Int,
    val city: Int,
    val createTime: Long,
    val defaultAvatar: Boolean,
    val description: String,
    val detailDescription: String,
    val djStatus: Int,
    val eventCount: Int,
    val expertTags: Any,
    val experts: Objects,
    val followMe: Boolean,
    val followTime: Any,
    val followed: Boolean,
    val followeds: Int,
    val follows: Int,
    val gender: Int,
    val inBlacklist: Boolean,
    val mutual: Boolean,
    val newFollows: Int,
    val nickname: String,
    val playlistBeSubscribedCount: Int,
    val playlistCount: Int,
    val privacyItemUnlimit: Objects,
    val province: Int,
    val remarkName: Any,
    val sCount: Int,
    val sDJPCount: Int,
    val signature: String,
    val userId: Int,
    val userType: Int,
    val vipType: Int
)