package com.franz.easymusicplayer.bean

import com.google.gson.JsonArray

data class BannerBean(
    val adDispatchJson: Any,
    val adLocation: Any,
    val adSource: Any,
    val adid: Any,
    val adurlV2: Any,
    val alg: String,
    val bannerId: String,
    val dynamicVideoData: Any,
    val encodeId: String,
    val event: Any,
    val exclusive: Boolean,
    val extMonitor: Any,
    val extMonitorInfo: Any,
    val logContext: Any,
    val monitorBlackList: Any,
    val monitorClick: Any,
    val monitorClickList: JsonArray,
    val monitorImpress: Any,
    val monitorImpressList: JsonArray,
    val monitorType: Any,
    val pic: String,
    val pid: Any,
    val program: Any,
    val requestId: String,
    val s_ctrp: String,
    val scm: String,
    val showAdTag: Boolean,
    val showContext: Any,
    val song: Any,
    val targetId: Int,
    val targetType: Int,
    val titleColor: String,
    val typeTitle: String,
    val url: Any,
    val video: Any
)